### ISSUE TITLE
Version: 80.0.2 npm install Failing

### ISSUE THREAD

**Issue by mohanelankuppan** [giggio/node-chromedriver#261] opened 2020-04-06 16:40 UTC
with the Latest Chrome Driver, below issue
06-Apr-2020 04:12:00	> chromedriver@80.0.2 install /home/farmer-portal/node_modules/chromedriver
06-Apr-2020 04:12:00	> node install.js
06-Apr-2020 04:12:00	
06-Apr-2020 04:12:01	internal/util.js:220
06-Apr-2020 04:12:01	    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'Function');
06-Apr-2020 04:12:01	    ^
06-Apr-2020 04:12:01	
06-Apr-2020 04:12:01	TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function
06-Apr-2020 04:12:01	    at promisify (internal/util.js:220:11)
06-Apr-2020 04:12:01	    at Object.<anonymous> (/home/farmer-portal/node_modules/chromedriver/node_modules/extract-zip/index.js:11:18)
06-Apr-2020 04:12:01	    at Module._compile (internal/modules/cjs/loader.js:654:30)
06-Apr-2020 04:12:01	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
06-Apr-2020 04:12:01	    at Module.load (internal/modules/cjs/loader.js:566:32)
06-Apr-2020 04:12:01	    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
06-Apr-2020 04:12:01	    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
06-Apr-2020 04:12:01	    at Module.require (internal/modules/cjs/loader.js:598:17)
06-Apr-2020 04:12:01	    at require (internal/modules/cjs/helpers.js:11:18)
06-Apr-2020 04:12:01	    at Object.<anonymous> (/home/farmer-portal/node_modules/chromedriver/install.js:14:20)

**Comment by esaari** [comment] 2020-04-06 19:53
Second this - seeing the same thing 
Can this be fixed asap? This is breaking builds for anybody that has `chromedriver: '^80.0.0'` in package.json.

**Comment by esaari** [comment] 2020-04-06 22:09
@giggio - normally I wouldn't @ someone but this is potentially breaking things for a lot of people

**Comment by giggio** [comment] 2020-04-07 02:11
Are you on Node.js 8? It is no longer supported.
If not, please send me the repro steps so I can verify.

**Comment by esaari** [comment] 2020-04-07 02:57
I'm on node 12.8.1. This should be pretty easy to reproduce, just do a `npm/yarn install` on any package.json that includes `  "chromedriver": "80.0.1"` as a dev dependency.

**Comment by kavisanghavi** [comment] 2020-04-07 15:19
Seeing the same thing. It started happening since yesterday I think.

**Comment by esaari** [comment] 2020-04-07 23:49
I investigated this more, the error on my end was because we were using a downstream job that I erroneously thought was running node 12 - it was running node 8.  You're correct in that this issue is most likely due to people needing to update node versions > 8.

**Comment by upendra-web** [comment] 2020-04-08 04:59
@esaari & @giggio , we are using node 9.4.0 and we are also facing the same issue

**Comment by GRme** [comment] 2020-04-08 12:57
The same for me too...

**Comment by giggio** [comment] 2020-04-09 01:29
Everyone, if no one send me repro steps I can't fix it.
I have tried it on Linux and on Windows and it works. Also, the build is working, you can see the badges on the home page, it works on Mac, Windows, Linux (on x64 and arm).
The supported Node.js versions are the ones that are LTS, which at the moment are 10, 12 and 13: https://nodejs.org/en/about/releases/
If you are on any version before 10, or 11, you are out of support from the Node.js team, and also this project.
So, please, send me repro steps for Linux or Windows and I'll do my best to fix it **on the supported versions**.

**Comment by mohanelankuppan** [comment] 2020-04-09 07:36
> 
> 
> Are you on Node.js 8? It is no longer supported.
> If not, please send me the repro steps so I can verify.

on Nodejs 8 ... Now what is the option?

**Comment by mohanelankuppan** [comment] 2020-04-09 07:54
> 
> 
> Everyone, if no one send me repro steps I can't fix it.
> I have tried it on Linux and on Windows and it works. Also, the build is working, you can see the badges on the home page, it works on Mac, Windows, Linux (on x64 and arm).
> The supported Node.js versions are the ones that are LTS, which at the moment are 10, 12 and 13: https://nodejs.org/en/about/releases/
> If you are on any version before 10, or 11, you are out of support from the Node.js team, and also this project.
> So, please, send me repro steps for Linux or Windows and I'll do my best to fix it **on the supported versions**.

npm install
Get this Error
> chromedriver@80.0.2 install /home/farmer-portal/node_modules/chromedriver
> node install.js

[91minternal/util.js:220
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'Function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function
    at promisify (internal/util.js:220:11)
    at Object.<anonymous> (/home/farmer-portal/node_modules/chromedriver/node_modules/extract-zip/index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/farmer-portal/node_modules/chromedriver/install.js:14:20)

**Comment by isjfk** [comment] 2020-04-09 12:40
We have same issue. After read this thread and upgrade NodeJS from v8.x to v12.x, the issue is fixed.

**Comment by Danita** [comment] 2020-04-09 13:08
Fails on NodeJS 10.8.0.

**Comment by giggio** [comment] 2020-04-09 15:18
@Danita I need repro steps and info. What SO, npm version, logs.

**Comment by giggio** [comment] 2020-04-09 15:20
If you are on a not supported version (8 for example) you should remain on version `80.0.1`. If you need to work with other versions of Chromedriver you can use the version parameters are explained on the readme:
https://github.com/giggio/node-chromedriver#versioning
Or
https://github.com/giggio/node-chromedriver#detect-chromedriver-version

**Comment by giggio** [comment] 2020-04-14 14:41
Ok, it seems we don't have repro steps. I'm closing this. If you have repro steps on a supported version please send it here and we can reopen this issue.

**Closed by giggio** 2020-04-14 14:41 UTC
