### ISSUE TITLE
Downloaded chromedriver file is not cached

### ISSUE THREAD

**Issue by mitar** [giggio/node-chromedriver#170] opened 2018-09-06 01:36 UTC
I would suggest that downloaded chromedriver file is cached into `~/.cache` or `~/.npm` somewhere. In this way if you are reinstalling app's `node_modules`, it will not be downloaded again.

This is useful inside CI builds to cache downloaded files between sessions. For example, CircleCI supports caching of files. It is not a good practice to cache `node_modules`, but one can cache `~/.cache` and `~/.npm` to speed things up.

This is how [Cypress NPM wrapper](https://docs.cypress.io/guides/guides/continuous-integration.html#Caching-the-Cypress-Binary) does it and it works great. They download a binary into `~/.cache` and then NPM wrapper just installs it from there.

**Comment by giggio** [comment] 2018-09-07 17:32
You can do that yourself, if you have the file downloaded you can install as shown in https://github.com/giggio/node-chromedriver#custom-binaries-file

And this is a duplicate of #72. A PR is welcome, if you'd like to send one.

**Closed by giggio** 2018-09-07 17:32 UTC
