### ISSUE TITLE
Version 2.25.3 doesn't install when using proxy

### ISSUE THREAD

**Issue by amiramix** [giggio/node-chromedriver#80] opened 2016-12-15 08:12 UTC
Version 2.21.2 installs without problems.

```bash
C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app>npm install chromedriver@2.21.2

> chromedriver@2.21.2 install C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app\node_modules\chromedriver
> node install.js

Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_win32.zip
Saving to C:\Users\MyUser\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
Receiving...
Received 788K...
Received 1570K...
Received 2353K...
Received 2537K total.
Extracting zip contents
Copying to target path C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app\node_modules\chromedriver\lib\chrome
driver
Done. ChromeDriver binary available at C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app\node_modules\chromed
river\lib\chromedriver\chromedriver.exe
myapp@0.0.3 C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app
`-- chromedriver@2.21.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})
```

However, on the same system installing version 2.25.3 fails:

```bash
C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app>npm install chromedriver@2.25.3
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to np
m

> chromedriver@2.25.3 install C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app\node_modules\chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.25/chromedriver_win32.zip
Saving to C:\Users\MyUser\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
Receiving...
ChromeDriver installation failed Error with http request: { 'content-type': 'text/html',
  'cache-control': 'no-cache',
  'content-length': '2150',
  'proxy-connection': 'Close' }
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "Q:\\105818.000_NODE_JS_441\\nodejs\\node.exe" "C:\\Users\\MyUser\\AppData\\Roaming\\npm\\node_modules\\np
m\\bin\\npm-cli.js" "install" "chromedriver@2.25.3"
npm ERR! node v4.4.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.25.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.25.3 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app\npm-debug.log
```

**Comment by ffoodd** [comment] 2016-12-15 15:26
I got almost the same trouble when trying to install gulp-axe-webdriver (which declare chromedriver as a dependency). I'm using latest Node / npm on Ubuntu.

The HTTP request for chromedriver is failing:
I got an error with HTTP request:
```
ChromeDriver installation failed Error with http request: { server: 'squid/2.7.STABLE9',
  date: 'Thu, 15 Dec 2016 15:11:17 GMT',
  'content-type': 'text/html',
  'content-length': '1151',
  'x-squid-error': 'ERR_UNSUP_REQ 0',
  'x-cache': 'MISS from host',
  'x-cache-lookup': 'NONE from host:port',
  via: '1.0 host:port (squid/2.7.STABLE9)',
  connection: 'close' }
```

As far as I understand this, chromedriver downloading is not event using my npm proxy configuration :/

**Comment by ffoodd** [comment] 2016-12-15 15:37
And I think this is because of this: https://github.com/giggio/node-chromedriver/commit/5ad68a36c3260760f1eb40d9c7906c6ea19c05b3

version 2.25.2 should work fine, I'll try.

**Comment by giggio** [comment] 2016-12-15 16:06
I can't repro. What are your variables values for `http_proxy` and `https_proxy`?
![image](https://cloud.githubusercontent.com/assets/334958/21231436/74f027ee-c2cf-11e6-9322-1e766a062270.png)
This proxy is running though docker. You can try it by running:

````bash
docker run -d -p 3128:3128 sameersbn/squid
````

Then, on PowerShell, set:

````powershell
$env:http_proxy='http://127.0.0.1:3128'
$env:https_proxy='http://127.0.0.1:3128'
````

See if you can repro.

**Comment by giggio** [comment] 2016-12-15 16:10
Also works with only `https_proxy` set:
![image](https://cloud.githubusercontent.com/assets/334958/21231660/3846e340-c2d0-11e6-9c03-868333d67d3f.png)

**Comment by giggio** [comment] 2016-12-15 16:11
Also works with only `http_proxy` set:
![image](https://cloud.githubusercontent.com/assets/334958/21231713/693b3e92-c2d0-11e6-9270-1c2c0b933e58.png)

**Comment by ffoodd** [comment] 2016-12-15 17:07
npm config list shows that my proxy is correctly configured. However I also have to use an id and password beside the host and port. Might it cause this error?

Apart from this, could you tell me which version of node and npm you're using? I'll try tomorrow with the exact same versions, just in case. Thanks for helping!

**Comment by giggio** [comment] 2016-12-15 17:47
The password will only be sent if they are already encoded in the url. For example, if the proxy url is `http://user:pass@github.com`, then we will use `user` as username, and `pass` as password. Please try your config with such settings and see if it works?
Also, `strict-ssl` might need to be set to false, if you have a certificate problem.
More info that might help: http://superuser.com/a/514263

**Comment by amiramix** [comment] 2016-12-15 21:10
In my case it's a corporate proxy so the credentials are not send in the URL but handled by a separate server from the proxy itself, It's like single-log-on. I can check any values you want but only when I am in the office on Friday.

**Comment by giggio** [comment] 2016-12-15 22:33
You can try to make a request using a simple script. Try this one, change the proxy Ip and port accordingly. This will try both http and https on the same server.

````js
const http = require('http');
const proxyIp = '127.0.0.1';
const proxyPort = 3128;
let req = http.request({
    host: proxyIp,
    port: proxyPort,
    method: 'GET',
    path: 'http://www.lambda3.com.br/'
}, res => {
    console.log(`Got status code ${res.statusCode}`);
    res.on('data', data => {
        // console.log(data.toString()); //uncomment to read
    });
    res.on('end', () => console.log("Done."));
});
req.on('error', err => {
    console.log(`Error: ${err}`)
})
req.end();

req = http.request({
    host: '127.0.0.1',
    port: proxyPort,
    method: 'GET',
    path: 'https://github.com/'
}, res => {
    console.log(`Got status code ${res.statusCode}`);
    res.on('data', data => {
        // console.log(data.toString()); //uncomment to read
    });
    res.on('end', () => console.log("Done."));
});
req.on('error', err => {
    console.log(`Error: ${err}`)
})
req.end()
````

**Comment by amiramix** [comment] 2016-12-16 08:00
I can confirm that no, version 2.25.2 also doesn't install:

```bash
C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app>npm install chromedriver@2.25.2
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to np
m

> chromedriver@2.25.2 install C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app\node_modules\chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.25/chromedriver_win32.zip
Saving to C:\Users\MyUser\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
Receiving...
ChromeDriver installation failed Error with http request: { 'content-type': 'text/html',
  'cache-control': 'no-cache',
  'content-length': '2150',
  'proxy-connection': 'Close' }
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "Q:\\105818.000_NODE_JS_441\\nodejs\\node.exe" "C:\\Users\\MyUser\\AppData\\Roaming\\npm\\node_modules\\np
m\\bin\\npm-cli.js" "install" "chromedriver@2.25.2"
npm ERR! node v4.4.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.25.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.25.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app\npm-debug.log
```

Version 2.21.2 still works fine:

```bash
C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app>npm install chromedriver@2.21.2
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to np
m

> chromedriver@2.21.2 install C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app\node_modules\chromedriver
> node install.js

Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_win32.zip
Saving to C:\Users\MyUser\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
Receiving...
Received 784K...
Received 1567K...
Received 2351K...
Received 2537K total.
Extracting zip contents
Copying to target path C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app\node_modules\chromedriver\lib\chrome
driver
Done. ChromeDriver binary available at C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app\node_modules\chromed
river\lib\chromedriver\chromedriver.exe
cosmos@0.0.4 C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app
`-- chromedriver@2.21.2
  +-- adm-zip@0.4.7
  +-- kew@0.5.0
  `-- npmconf@2.1.2
    +-- config-chain@1.1.11
    | `-- proto-list@1.2.4
    +-- once@1.3.3
    +-- semver@4.3.6
    `-- uid-number@0.0.5

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})
```

Will try the script in a few moments.

**Comment by ffoodd** [comment] 2016-12-16 08:24
I tried a few things. For now my npm config looks like:
```
https-proxy = "http://id:pass@host:port/"
proxy = "http://id:pass@host:port/"
strict-ssl = false
```
But I'm still facing the HTTP request error.

I tried to install another version, 2.25.1 worked but 2.25.2 didn't. I hope it'll help to find out what's happening :)

**Comment by ffoodd** [comment] 2016-12-16 09:35
I just had a look at diff between 2.25.1 (which I can install) and 2.25.2 (which I can't) and the only change is the use of `https` as default download link protocol :/

I don't understand why it's preventing me from downloading it…

**Comment by amiramix** [comment] 2016-12-16 09:48
The output from the script, not sure if this is what you expected?

```bash
C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app>node test.js
Got status code 407
Done.
Got status code 200
Done.
```

Please note that in my environment there is no one proxy but a few dozens of them. The proxy configuration file used by IE is 6000 lines long. Different websites may be going to different proxy servers depending on the domain.

In particular, the response 200 from github.com above isn't because the page has loaded correctly but because github.com is normally blocked and the proxy returned a page with information that it's blocked and how to request access. The proxy configuration file uses a different proxy when accessing github.com.

I modified the script a bit and this is what it returns:

```bash
C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app>node test.js
Got status code 500 for https://chromedriver.storage.googleapis.com/2.25/chromedriver_win32.zip
{"content-type":"text/html","cache-control":"no-cache","content-length":"2150","proxy-connection":"Close"}
Done.

Got status code 407 res https://github.com/
{"via":"1.1 10.233.152.41 (McAfee Web Gateway 7.5.2.11.0.22125)","date":"Fri, 16 Dec 2016 08:46:02 GMT","content-type":"
text/html","cache-control":"no-cache","content-length":"3415","proxy-connection":"Close","proxy-authenticate":"Negotiate
, NTLM"}
Done.

Got status code 200 for http://chromedriver.storage.googleapis.com/2.21/chromedriver_win32.zip
{"age":"654","date":"Fri, 16 Dec 2016 08:35:08 GMT","etag":"\"8a93dc3ff02ef9bc3161dd4b20f87215\"","server":"UploadServer
","expires":"Fri, 16 Dec 2016 09:35:08 GMT","x-goog-hash":"crc32c=HyEtRg==, md5=ipPcP/Au+bwxYd1LIPhyFQ==","content-type"
:"application/x-zip-compressed","accept-ranges":"bytes","cache-control":"public, max-age=3600","last-modified":"Tue, 26
Jan 2016 06:47:03 GMT","content-length":"2598298","content-language":"en","proxy-connection":"Close","x-goog-generation"
:"1453790823425000","x-goog-storage-class":"STANDARD","x-guploader-uploadid":"AEnB2UrCRhgFoYHDGDZ-vM_8w4dpCVrJS7Y3EROYSz
SwJxB9n1zc5cxljrNPoEauOien41uLIaPnYViKC8qN4d32QRWNkZdHL861jIkIAPbCJeuR3levd54","x-goog-metageneration":"1","x-goog-store
d-content-length":"2598298","x-goog-stored-content-encoding":"identity"}
Done.
```

Note the difference between the URL when fetching version 2.25 and 2.21 - 2.21 uses http whereas 2.25 uses https. When I change the 2.25's URL to http it works:

```bash
C:\Users\Public\Documents\CYGWIN\home\MyUser\work2\my_app>node test.js
Got status code 407 res https://github.com/
{"via":"1.1 10.233.152.41 (McAfee Web Gateway 7.5.2.11.0.22125)","date":"Fri, 16 Dec 2016 08:56:45 GMT","content-type":"
text/html","cache-control":"no-cache","content-length":"3415","proxy-connection":"Close","proxy-authenticate":"Negotiate
, NTLM"}
Done.

Got status code 200 for http://chromedriver.storage.googleapis.com/2.21/chromedriver_win32.zip
{"age":"3143","date":"Fri, 16 Dec 2016 08:04:22 GMT","etag":"\"8a93dc3ff02ef9bc3161dd4b20f87215\"","server":"UploadServe
r","expires":"Fri, 16 Dec 2016 09:04:22 GMT","x-goog-hash":"crc32c=HyEtRg==, md5=ipPcP/Au+bwxYd1LIPhyFQ==","content-type
":"application/x-zip-compressed","accept-ranges":"bytes","cache-control":"public, max-age=3600","last-modified":"Tue, 26
 Jan 2016 06:47:03 GMT","content-length":"2598298","content-language":"en","proxy-connection":"Close","x-goog-generation
":"1453790823425000","x-goog-storage-class":"STANDARD","x-guploader-uploadid":"AEnB2UopLmJL7E-xIok1yor5byV69l2b98zeCPq_1
qAO1c-m6eFcrm3sowiiTWfLcA_3oPBeSZUxgb9K--Tj6ZPjake9qUvvm-A0erCHUBHluCl65Zv21Tg","x-goog-metageneration":"1","x-goog-stor
ed-content-length":"2598298","x-goog-stored-content-encoding":"identity"}
Done.

Got status code 200 for http://chromedriver.storage.googleapis.com/2.25/chromedriver_win32.zip
{"age":"0","date":"Fri, 16 Dec 2016 08:56:45 GMT","etag":"\"2727729883ac960c2edd63558f08f601\"","server":"UploadServer",
"expires":"Fri, 16 Dec 2016 09:56:45 GMT","x-goog-hash":"crc32c=kFmGBQ==, md5=JydymIOslgwu3WNVjwj2AQ==","content-type":"
application/x-zip-compressed","accept-ranges":"bytes","cache-control":"public, max-age=3600","last-modified":"Sat, 22 Oc
t 2016 05:25:54 GMT","content-length":"3521408","content-language":"en","proxy-connection":"Close","x-goog-generation":"
1477113954064000","x-goog-storage-class":"STANDARD","x-guploader-uploadid":"AEnB2UodzV-D_jGCBX62Fq9oNyQ8y7jWKFP5_eQxbS5x
Yy5mXuFY1ooF3Zfqeu3uC7yEZdnbTPP_n5RN_tj0OO4sXJ55_bEO270Q462U7NI7aY8cIzMTOwM","x-goog-metageneration":"1","x-goog-stored-
content-length":"3521408","x-goog-stored-content-encoding":"identity"}
Done.
```

**Comment by giggio** [comment] 2016-12-16 17:15
@amiramix I am not sure why node.js would succeed when requesting with a proxy and http:
http://chromedriver.storage.googleapis.com/2.25/chromedriver_win32.zip
But fail when requesting with a proxy and https:
https://chromedriver.storage.googleapis.com/2.25/chromedriver_win32.zip

Can you try with a different language? Here is a powershell you can try, replace the proxy values:

````powershell
Add-Type -AssemblyName System.Net.Http
$proxy = new-object System.Net.WebProxy -ArgumentList '127.0.0.1',3128
$hch = New-Object System.Net.Http.HttpClientHandler
$hch.Proxy = $proxy
$hch.UseProxy = $true
$hc = New-Object System.Net.Http.HttpClient $hch
$response = $hc.GetAsync('https://chromedriver.storage.googleapis.com/2.25/chromedriver_win32.zip').Result
$response.StatusCode
````

**Comment by amiramix** [comment] 2016-12-16 17:53
I will try it on Monday. I would rather ask what browsers do differently than node.js that it works in browsers but not in node.js...

**Comment by amiramix** [comment] 2016-12-19 12:15
Powershell returned just "OK".

**Comment by giggio** [comment] 2016-12-20 01:43
@amiramix This means PowerShell is able to go through your firewall and get the file. But node, according to your previous post, is not. I am not sure why.

**Comment by amiramix** [comment] 2016-12-20 17:43
Node.js still goes through proxy for http, the only problem is with https.

I am not sure if it matters but the proxy uses a self-signed certificate. We had to specifically disable verifying the certificate chain for git, github or internal bitbucket. Some browsers don't even load CSS when opening github through that proxy because of certificate problems. This, however, works fine in IE, which isn't usually a problem since IE is the only approved browser.. Could that be related?

**Comment by giggio** [comment] 2016-12-20 17:52
@amiramix yes, it can be related. Try setting `strict-ssl` to false.

**Comment by amiramix** [comment] 2016-12-20 17:56
where?

**Comment by artemrudenko** [comment] 2016-12-21 08:19
Hi all, having the same issue. 
Setting the strict-ssl=false did't help me. 
I tried to download zip and to change cdnUrl(install.js) to use http instead of http. Then run `node install.js` and finally driver getting installed.

**Comment by amiramix** [comment] 2016-12-21 16:16
@giggio Can you please have a look at these:

http://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request
https://github.com/nodejs/node/issues/5258#issuecomment-184762392

Is there any way I can temporarily add

    process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

to `node-chromedriver`'s `install.js` to test it without having to fork the entire repo and creating a copy of the package in npmjs.org?

Maybe through some option?

**Comment by giggio** [comment] 2016-12-21 20:51
Yes, use `npm link` to test. https://docs.npmjs.com/cli/link
Basically fork this repo, clone your fork, add whatever code you want, `npm link` it, then run the install.

**Comment by amiramix** [comment] 2016-12-22 14:28
Thanks, I will have look into that but probably next year. Have a good one!

**Comment by giggio** [comment] 2016-12-22 21:49
Ok, I am closing the issue until then, if you are able to find out what the problem is let me know.

**Closed by giggio** 2016-12-22 21:49 UTC
