### ISSUE TITLE
npm install fails with chromedriver@2.15.1

### ISSUE THREAD

**Issue by dirk-butze** [giggio/node-chromedriver#30] opened 2015-05-27 13:41 UTC
```
> chromedriver@2.15.1 install /usr/safe/bamboo/xml-data/build-dir/RTC-RTCGWCIPLAYGROUND20-PRUT/acceptance-tests-javascript/node_modules/chromedriver
> node install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'boom'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/safe/bamboo/xml-data/build-dir/RTC-RTCGWCIPLAYGROUND20-PRUT/acceptance-tests-javascript/node_modules/request/node_modules/hawk/lib/index.js:3:33)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
|

alternatively it complained about missing 'core-util-is' rather than 'boom':

> chromedriver@2.15.1 install /usr/safe/bamboo/xml-data/build-dir/RTC-RTCGWCIPLAYGROUND20-PRUT/acceptance-tests-javascript/node_modules/chromedriver
> node install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/safe/bamboo/xml-data/build-dir/RTC-RTCGWCIPLAYGROUND20-PRUT/acceptance-tests-javascript/node_modules/request/node_modules/bl/node_modules/readable-stream/lib/_stream_duplex.js:39:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
-

...

npm ERR! Linux 2.6.32-431.17.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.15.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.15.1 install script 'node install.js'.
npm ERR! This is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

alternatively it failed with Exit status 8 rather than 1:

npm ERR! Linux 2.6.32-431.17.1.el6.x86_64
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.32
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.15.1 install: `node install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the chromedriver@2.15.1 install script 'node install.js'.
npm ERR! This is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.
```
-----------------------------------------------------------------------------------------------------------------------------

Also I tried cleaning the npm cache:
```
npm cache clean -f
rm -rf node_modules/
```
but also upgrading npm from 1.3.6 to v2.10.1 as well as node v0.10.32 to 0.12.4. However nothing of that fixed it.

**Comment by dirk-butze** [comment] 2015-05-27 13:56
Sticked ChromeDriver to 2.15.0 which works:
```
git diff package.json | grep chrome
-      "chromedriver": "^2.12.0",
+      "chromedriver": "2.15.0",

> chromedriver@2.15.0 install /usr/safe/bamboo/xml-data/build-dir/RTC-RTCGWCIPLAYGROUND20-PRUT/acceptance-tests-javascript/node_modules/chromedriver
> node install.js

Downloading http://chromedriver.storage.googleapis.com/2.15/chromedriver_linux64.zip
Saving to /tmp/chromedriver/chromedriver_linux64.zip
Receiving...
Received 782K...
Received 1564K...
Received 2228K total.
Extracting zip contents
Copying to target path /usr/safe/bamboo/xml-data/build-dir/RTC-RTCGWCIPLAYGROUND20-PRUT/acceptance-tests-javascript/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /usr/safe/bamboo/xml-data/build-dir/RTC-RTCGWCIPLAYGROUND20-PRUT/acceptance-tests-javascript/node_modules/chromedriver/lib/chromedriver/chromedriver

...

chromedriver@2.15.0 node_modules/chromedriver
âââ kew@0.5.0
âââ adm-zip@0.4.7
âââ mkdirp@0.5.1 (minimist@0.0.8)
âââ npmconf@2.1.2 (uid-number@0.0.5, inherits@2.0.1, osenv@0.1.1, ini@1.3.3, once@1.3.2, nopt@3.0.2, config-chain@1.1.8, semver@4.3.4)
âââ rimraf@2.3.4 (glob@4.5.3)
```

**Comment by giggio** [comment] 2015-05-27 16:52
@dirk-butze Yeah, I have not been looking back to previous versions. Is it working for you then?

**Comment by dirk-butze** [comment] 2015-05-28 09:18
@giggio Sorry I am not sure what you mean. As I said pining "chromedriver": "2.15.0" works for me.

**Comment by giggio** [comment] 2015-05-30 20:07
@dirk-butze Sorry, I had understood incorrectly.

Issue #31 may also be related to the change that happened between 2.15.0 and 2.15.1, which came from #27, from @alexdavid. I am waiting to hear from @panuhorsmalahti on #31.

I haven't been able to reproduce it on Linux or Windows. @alexdavid do you have any idea of what might be happening? I might need to revert it if we don't find a solution. But first, I need to be able to reproduce it. @dirk-butze, please find me a way to confirm the bug.

**Comment by alexdavid** [comment] 2015-05-30 20:35
Yeah this is strange, I can't reproduce this either, but the error is definitely related to my change in #27:
* [boom](https://www.npmjs.com/package/boom) is a dep of [hawk](https://www.npmjs.com/package/hawk) which is a dep of [request](https://www.npmjs.com/package/request)
* [core-util-is](https://www.npmjs.com/package/core-util-is) is a dep of [readable-stream](https://www.npmjs.com/package/readable-stream) which is a dep of [bl](https://www.npmjs.com/package/bl) which is a dep of [request](https://www.npmjs.com/package/request)

@dirk-butze, can you try installing `request` and verify that these paths exist:
* `node_modules/request/node_modules/hawk/node_modules/boom`
* `node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/core-util-is`

Also, what platform are you running into this issue on?

**Comment by solshark** [comment] 2015-06-02 11:20
Same issue on Linux

**Comment by alexdavid** [comment] 2015-06-03 10:11
@solshark could you verify that `npm install requests` succeeds and the two paths I quoted above exist?

Thanks!

**Comment by arty-name** [comment] 2015-06-30 09:01
I can quite reliably reproduce it with a very simple package.json:

      "dependencies": {
        "request": "2.58.0"
      },
      "devDependencies": {
        "chromedriver": "2.15.1"
      },

Looks like chromedriver tries to use the request module before it's ready:

    > chromedriver@2.15.1 install /home/treguben/dev/here.com/node_modules/chromedriver
    > node install.js

    module.js:338
        throw err;
              ^
    Error: Cannot find module 'is-property'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/home/treguben/dev/here.com/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/index.js:1:80)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)

**Comment by alexdavid** [comment] 2015-07-01 03:13
@arty-name Auhh I see what the issue is here. I guess npm does not guarantee that dependencies are installed by the time a post-install hook runs. Any project that requires node-chromedriver and request has a chance to fail.

The fact that this repo has any dependencies that the post-install hook depends on is a race condition but a very unlikely one since all of the current dependencies are very small. [Request has a lot of dependencies](https://github.com/request/request/blob/master/package.json), so this is causing this issue and probably also #31.

It looks like this might be a wontfix from NPM: https://github.com/npm/npm/issues/2872

@giggio I suppose the best course of action is revert 97ad7e87af6b70772e70c9fcf5e85b6339cb2d6d and I can re-implement `NO_PROXY` support by hand :(

I guess in the future we need to be cautious of libraries added to dependencies of this project. If they are large then there is a chance of install failing

**Comment by arty-name** [comment] 2015-07-01 06:04
@isaacs says there:

> If you're actually installing some binary for the target architecture, then you should be using gyp, not an external JS module.

Maybe that would be a better approach to download a chromedriver binary?

**Comment by giggio** [comment] 2015-07-05 02:38
@alexdavid Ok, I will revert it. As far as I understand this is a bug, and they are aware of it. I think npm might fix it: https://github.com/npm/npm/issues/4134
When (if) they fix it, we can bring it back.
This a bad bug, as if anyone has on their package.json:

* adm-zip
* kew
* mkdirp
* npmconf
* request
* rimraf

The same problem will show up.

@arty-name I am not sure about using gyp, as we are not compiling anything, and, AFAIK, gyp is used for that, right?
Does anyone see any other solution here?

**Comment by giggio** [comment] 2015-07-05 02:45
BTW, I have confirmed the bug with @arty-name  package.json example. After reverting the problem was fixed. I will commit, push and publish. If we find a better solution later we can implement it.

**Comment by giggio** [comment] 2015-07-05 02:52
Version 2.15.2 has been published.

**Closed by giggio** 2015-07-05 02:52 UTC
Labels: bug

**Comment by arty-name** [comment] 2015-07-05 07:41
@giggio I also had an idea that gyp is for compiling, but maybe it can also fetch binaries

**Comment by isaacs** [comment] 2015-07-05 17:07
Gyp can run arbitrary programs.  So yes, it can do whatever you need it to.

**Comment by charlierudolph** [comment] 2015-09-29 19:01
Can #27 be merged back in?  With npm 3, install scripts don't run until everything has been installed.

**Comment by giggio** [comment] 2015-09-29 20:20
@charlierudolph Have you tried with npm 2 and npm 3? Can you confirm it did not work before and works now?
Npm 3 has just rtm'ed. I would still wait a while until everyone updates.

**Comment by giggio** [comment] 2015-09-29 20:21
@isaacs When is node expected to be released with NPM 3? 4.x? Any idea of a timeframe?
