### ISSUE TITLE
Unable to install version 2.30.1 in ubuntu

### ISSUE THREAD

**Issue by gentiger** [giggio/node-chromedriver#110] opened 2017-06-25 04:40 UTC
Met this error when tying to install chromedriver even using NPM3 

verbose stack Error: chromedriver@2.30.1 install: `node install.js`
1278 verbose stack spawn ENOENT
1278 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
1278 verbose stack     at emitTwo (events.js:87:13)
1278 verbose stack     at ChildProcess.emit (events.js:172:7)
1278 verbose stack     at maybeClose (internal/child_process.js:821:16)
1278 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
1279 verbose pkgid chromedriver@2.30.1
1280 verbose cwd /projects/frappe-bench
1281 error Linux 3.10.0-514.10.2.el7.x86_64
1282 error argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
1283 error node v4.2.6
1284 error npm  v3.5.2
1285 error file sh
1286 error code ELIFECYCLE
1287 error errno ENOENT
1288 error syscall spawn
1289 error chromedriver@2.30.1 install: `node install.js`
1289 error spawn ENOENT
1290 error Failed at the chromedriver@2.30.1 install script 'node install.js'.
1290 error Make sure you have the latest version of node.js and npm installed.
1290 error If you do, this is most likely a problem with the chromedriver package,
1290 error not with npm itself.
1290 error Tell the author that this fails on your system:
1290 error     node install.js
1290 error You can get information on how to open an issue for this project with:
1290 error     npm bugs chromedriver
1290 error Or if that isn't available, you can get their info via:
1290 error     npm owner ls chromedriver
1290 error There is likely additional logging output above.

**Comment by giggio** [comment] 2017-06-26 22:26
This is a known problem in npm3, not in the installer. This is a duplicate of #109. See this comment:
https://github.com/giggio/node-chromedriver/issues/109#issuecomment-310551960
Update to a newer npm version with `npm i -g npm`.

**Closed by giggio** 2017-06-26 22:26 UTC
