### ISSUE TITLE
detect_chromedriver_version not working as expected with chrome >= 115

### ISSUE THREAD

**Issue by db798** [giggio/node-chromedriver#420] opened 2023-07-21 15:50 UTC
We have updated our code to use version 114.0.3 of this package due to the changes for chrome 115. 

We have noticed that the install doesn't work correctly when `detect_chromedriver_version=true` is defined in your `.npmrc`. There doesn't seem to be any error on the actual install but we get this error when trying to run our tests(using webdriverio) `unknown error: cannot find Chrome binary`.

Once we remove detect_chromedriver_version from the `.npmrc` everything works as expected. Could this be an issue with how the package is downloading from the new locations?

This happens with both chrome 115.0.5790.102 and 115.0.5790.98. I am using an arm64 mac.

**Comment by giggio** [comment] 2023-07-24 14:36
@db798 I don't have a Mac to test it at the moment, can you post the logs?

**Comment by db798** [comment] 2023-07-24 16:55
Not sure if these logs are useful but I've pull the latest code from this repo. 

When I include `detect_chromedriver_version=true` in my `.npmrc` here are the logs from the install - 

```
> node install.js

Your Chrome version is 115.0.5790.102
Finding Chromedriver version.
Chromedriver version is 115.0.5790.102.
Compatible ChromeDriver version is 115.0.5790.102
Saving to file: /var/folders/sz/kjnt747s5dx586hmnslfp9yh0000gp/T/115.0.5790.102/chromedriver/chromedriver-mac-arm64.zip
ChromeDriver binary exists. Validating...
ChromeDriver is already available at '/var/folders/sz/kjnt747s5dx586hmnslfp9yh0000gp/T/115.0.5790.102/chromedriver/chromedriver-mac-arm64/chromedriver'.
Copying from /var/folders/sz/kjnt747s5dx586hmnslfp9yh0000gp/T/115.0.5790.102/chromedriver/chromedriver-mac-arm64 to target path /Users/dbreen/Downloads/node-chromedriver-main/lib/chromedriver
Fixing file permissions.
Done. ChromeDriver binary available at /Users/dbreen/Downloads/node-chromedriver-main/lib/chromedriver/chromedriver
```

When I remove, `detect_chromedriver_version=true`. 
```
> node install.js

Saving to file: /var/folders/sz/kjnt747s5dx586hmnslfp9yh0000gp/T/114.0.5735.90/chromedriver/chromedriver_mac_arm64.zip
ChromeDriver binary exists. Validating...
ChromeDriver is already available at '/var/folders/sz/kjnt747s5dx586hmnslfp9yh0000gp/T/114.0.5735.90/chromedriver/chromedriver'.
Copying from /var/folders/sz/kjnt747s5dx586hmnslfp9yh0000gp/T/114.0.5735.90/chromedriver to target path /Users/dbreen/Downloads/node-chromedriver-main/lib/chromedriver
Fixing file permissions.
Done. ChromeDriver binary available at /Users/dbreen/Downloads/node-chromedriver-main/lib/chromedriver/chromedriver
```

Seems like the `ChromeDriver is already available` path is different?

**Comment by yorkmoy** [comment] 2023-07-24 18:37
There is a bug filed against Chromedriver 15 that sounds like it is the cause of this issue reported here. If I am reading the bug correctly, it sounds like chromedriver is assuming the Chrome for Testing binary is being used instead of the regular Chrome binary currently installed in the environment. https://bugs.chromium.org/p/chromium/issues/detail?id=1466427

**Comment by giggio** [comment] 2023-07-24 22:59
@db798 in both cases, detecting or not, the binary is available in the end. It does not seem to be a problem with this package, it might the problem @yorkmoy mentioned.
You could try to run `/Users/dbreen/Downloads/node-chromedriver-main/lib/chromedriver/chromedriver` directly and see if it runs. If it does not run, it is probably not a problem with this package.
You could try removing that file, and running install again, to see if downloads and installs properly, and then rerun the binary and see if it works. Before, also delete `/var/folders/sz/kjnt747s5dx586hmnslfp9yh0000gp/T/114.0.5735.90/` and `/var/folders/sz/kjnt747s5dx586hmnslfp9yh0000gp/T/115.0.5790.102`, which are probably your temp directories.
After running, post the logs here.

**Comment by db798** [comment] 2023-07-25 09:33
Yes, this does not look like an issue with this package. 

After removing the temp folders, here are the logs,

without detect, 
```
Saving to file: /var/folders/sz/kjnt747s5dx586hmnslfp9yh0000gp/T/114.0.5735.90/chromedriver/chromedriver_mac_arm64.zip
Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac_arm64.zip
Received 1040K...
Received 2080K...
Received 3120K...
Received 4160K...
Received 5200K...
Received 6240K...
Received 7280K...
Received 7575K total.
Extracting zip contents to /var/folders/sz/kjnt747s5dx586hmnslfp9yh0000gp/T/114.0.5735.90/chromedriver.
Copying from /var/folders/sz/kjnt747s5dx586hmnslfp9yh0000gp/T/114.0.5735.90/chromedriver to target path /Users/dbreen/Downloads/node-chromedriver-main/lib/chromedriver
Fixing file permissions.
Done. ChromeDriver binary available at /Users/dbreen/Downloads/node-chromedriver-main/lib/chromedriver/chromedriver
```
with detect
```
Your Chrome version is 115.0.5790.102
Finding Chromedriver version.
Chromedriver version is 115.0.5790.102.
Compatible ChromeDriver version is 115.0.5790.102
Saving to file: /var/folders/sz/kjnt747s5dx586hmnslfp9yh0000gp/T/115.0.5790.102/chromedriver/chromedriver-mac-arm64.zip
Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
Downloading from file:  https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/mac-arm64/chromedriver-mac-arm64.zip
Received 1039K...
Received 2079K...
Received 3119K...
Received 4159K...
Received 5199K...
Received 6223K...
Received 7263K...
Received 8190K total.
Extracting zip contents to /var/folders/sz/kjnt747s5dx586hmnslfp9yh0000gp/T/115.0.5790.102/chromedriver.
Copying from /var/folders/sz/kjnt747s5dx586hmnslfp9yh0000gp/T/115.0.5790.102/chromedriver/chromedriver-mac-arm64 to target path /Users/dbreen/Downloads/node-chromedriver-main/lib/chromedriver
Fixing file permissions.
Done. ChromeDriver binary available at /Users/dbreen/Downloads/node-chromedriver-main/lib/chromedriver/chromedriver
```

With both versions, I can run `/Users/dbreen/Downloads/node-chromedriver-main/lib/chromedriver/chromedriver` and chromedriver starts successfully.

As an extra step, I also enabled chromedriver logs in webdriverio and I can see that chromedriver is starting successfully there too. So everything looks to be working as expected with this package, seems like the Chromedriver bug mentioned is the likely cause of my issues.

**Comment by giggio** [comment] 2023-07-25 21:53
Ok, I'll close the issue, if you find to be a problem with this package just comment here and I'll reopen, or open a new one.

**Closed by giggio** 2023-07-25 21:53 UTC
Labels: bug
