### ISSUE TITLE
Download not working using a Proxy on Windows

### ISSUE THREAD

**Issue by thibautvs** [giggio/node-chromedriver#85] opened 2017-01-09 09:33 UTC
Hello,

Just wanted to raise an issue regarding the installation of Chromedriver on Windows behind a corporate proxy. Here's some additional information following a debugging session of install.js:

- The proxy address was correctly retrieved from the global config of NPM. Also, I set both proxy and https-proxy values in my global NPM config.
- The proxy is using regular http.
- The download was not starting and I received an HTTP 400 (bad request) from the server
- I could manage to have the download process to start by removing `requestOptions.path`
- However the download stopped pretty quickly, downloading only about 22 bytes, resulting in a corrupt archive
- I tried to install the package at home, without a proxy, and it all went fine
- I must also point out that everything related to network access works perfectly with the proxy config I have: web access, downloading NPM packages, downloading Atom packages etc

I hope these informations will help you identify & fix the issue.

Thanks,

Thibaut

**Comment by giggio** [comment] 2017-01-11 14:29
@thibautvs I can't repro it. I am on Windows now. I just tested with a Squid proxy and it worked fine. Can you investigate and send a PR?

**Comment by jsmorris** [comment] 2017-02-06 21:48
I am also encountering this issue.  More info if it helps...

node: 6.9.4
npm: 3.10.10
Win 8.1 Enterprise (6.3.9600) behind a corporate proxy
proxy and https-proxy set in my .npmrc file

I can install up to 2.25.1.  I cannot install versions 2.25.2 - 2.27.2

The cdnUrl changed from 'http' to 'https' and the change is here https://github.com/giggio/node-chromedriver/compare/2.25.1...2.25.2

Something cannot handle https in my setup.

**Comment by gluxhappy** [comment] 2017-02-22 07:07
Hi, @giggio , i also have this issue, and after some investigation, i found it is a proxy issue in /install.js
[Current proxy solution](https://github.com/giggio/node-chromedriver/blob/master/install.js#L120) will not work as expected if proxy server is using HTTP and target server is using HTTPS.
For example, proxy server is "```http```://a.proxy.server:8080", the target is  "```https```://chromedriver.storage.googleapis.com" is this project. It wouldn't work.

Please refer this article for more detail, [proxy-requests-in-node-js](https://www.vanamco.com/2014/06/24/proxy-requests-in-node-js/) 

----------------------------------
A workaround/temporary solution for this issue is set an environment variable before execute ```npm install``` to force install.js use http

On windows ```set CHROMEDRIVER_CDNURL=http://chromedriver.storage.googleapis.com```
On linux ```export CHROMEDRIVER_CDNURL=http://chromedriver.storage.googleapis.com```

**Comment by giggio** [comment] 2017-03-11 20:16
@gluxhappy ok, I can't repro that, but I am happy to integrate a PR.

**Comment by gluxhappy** [comment] 2017-03-17 09:54
@giggio I suggest you to use [request](https://github.com/request/request) instead implementing it by yourself.

**Comment by kiran-redhat** [comment] 2017-04-06 23:16
I am facing same and the issue is: 'ChromeDriver installation failed Error with http request' as @gluxhappy said.

Bye setting following on windows fixed temporarily: 
set CHROMEDRIVER_CDNURL=http://chromedriver.storage.googleapis.com

**Comment by giggio** [comment] 2017-06-08 00:24
We just published 2.29.1 to NPM, it probably solves the problem. I am closing the issue, please reopen if you find it does not solve it.

**Closed by giggio** 2017-06-08 00:24 UTC
