### ISSUE TITLE
Install Fails on OSX 10.11.3

### ISSUE THREAD

**Issue by chrisalexander55** [giggio/node-chromedriver#44] opened 2016-03-18 15:34 UTC
ENV:
  Node 0.12.7
  NPM 3.8.0
  OSX 10/11/3

I've been fighting with getting chromedriver installed via NPM and constantly run into the following exception:

npm ERR! Darwin 15.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v3.8.0
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.21.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromedriver@2.21.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

I've tried running as sudo, still throws. Any suggestions?

**Comment by vspiewak** [comment] 2016-03-23 09:58
Same here on Ubuntu 14.04, NPM 3.7.3, Node v5.9.0

**Comment by leolord** [comment] 2016-03-26 02:33
Same problem on OS X 10.11.4 (15E65), and same error log.

**Comment by techbirds** [comment] 2016-03-30 06:47
OSX 10.11.4 (15E65)

npm ERR! chromedriver@2.21.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.21.2 install script 'node install.js'.
npm ERR! This is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! node v0.12.12
npm ERR! npm  v2.14.9

**Comment by romoo** [comment] 2016-04-06 06:40
Same here: Mac 10.11.4, node v4.3.1, npm  v3.7.5

**Comment by ginny315** [comment] 2016-05-04 03:44
Same here: Mac 10.10.5 node v4.4.0 npm 2.14.20

**Comment by Harbon** [comment] 2016-05-09 07:18
any solution?

**Comment by farhad-arjmand** [comment] 2016-05-14 08:08
the issue has been fixed with
"chromedriver": "^2.21.2", => to "chromedriver": "*",
and install nodejs 6

**Comment by Razzeee** [comment] 2016-05-20 11:26
@farhad-arjmand doesn't seem to help for me

https://github.com/giggio/node-chromedriver/issues/46 is also a duplicate of this

**Comment by ebo20** [comment] 2016-06-01 21:34
Still running into this issue as well: 
OS X 10.10.5  
node 4.4.5 
npm 2.15.5

**Comment by giggio** [comment] 2016-08-03 00:02
I can't repro it. Can anyone that is having the problem debug it?

**Comment by chrisalexander55** [comment] 2016-08-03 00:04
Giovanni,

It appears that the issue was tied to the proxy/firewall at my company.
Please close this issue as it is no longer valid. Thanks!

**Closed** 2016-08-03 00:33 UTC

**Comment by XxJChavezxX** [comment] 2016-08-16 21:57
Anyone still having this issue? I just ran into this.  By doing a simple `npm install chromedriver` @chrisalexander55  what was the solution you reached?

**Comment by chrisalexander55** [comment] 2016-08-16 22:49
When I executed the command outside my company's firewall it installed
without incident. That's all I got...
